name: cron-audit-committee

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  job_id:
    name: cron-audit-committee
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: |
        python src/reference.py --key KomiteAudit
    - name: Commit changes
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git config --global user.email ${USER_EMAIL}
        git config --global user.name ${USER_NAME}
        git config pull.rebase false
        git remote set-url origin https://${USER_NAME}:${ACCESS_TOKEN}@github.com/${USER_NAME}/indonesia-stock-exchange.git
        git pull origin main
        git add -A
        git diff-index --quiet HEAD || git commit -m "Update audit committee data"
        git push origin main
