name: financial-statement

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    name: financial-statement
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: |
        python src/financial_statement.py --year 2019 --audit TW2  --quarter II
        rm -rf tmp/
    - name: Commit changes
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git config --global user.email ${USER_EMAIL}
        git config --global user.name ${USER_NAME}
        git config pull.rebase false
        git remote set-url origin https://${USER_NAME}:${ACCESS_TOKEN}@github.com/${USER_NAME}/indonesia-stock-exchange.git
        git pull origin main
        git add -A
        git diff-index --quiet HEAD || git commit -m "Update financial statement data"
        git push origin main
